theme: jekyll-theme-minimal
title: Pustaka Kalender Jawa
description: Kalender Jawa iku sistem kalender adhedhasar bulan.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one